### ISSUE TITLE
rsw-watch can't exit

### ISSUE THREAD

**Issue by HomyeeKing** [rwasm/rsw-rs#7]
rsw still watch the project even  have exited(ctrl + c) the program

should listen exit event, then exit watch mode.

**Comment by lencx** [comment]
I can't reproduce the problem for now, can you record a video?

**Comment by HomyeeKing** [comment]
just do the save action in edit panel

https://user-images.githubusercontent.com/49113249/205227252-2baecba3-2e25-4eee-b7b1-240b43c11487.mov

**Comment by lencx** [comment]
Try `ctrl + z`?

**Comment by lencx** [comment]
I can't locate your problem for now, if possible, you can pull the source code and debug it yourself. No other users have reported similar issues so far.

**Comment by HomyeeKing** [comment]
OK, I am a new Rustaceans and learning the rust docs recently, maybe send a PR later

**Comment by HomyeeKing** [comment]
this issue can be reproduced by run `rsw watch & vite`, rsw watch is fine but running concurrently at background, can't be exited

**Comment by HomyeeKing** [comment]
could you  please add the `CONTRIBUTE` guide, I have no idea how to debug the local build binary.  Does it need an example directory?  @lencx

**Comment by lencx** [comment]
Sorry, I'm currently busy with other things and don't have time to write the contributor guidelines. It is recommended that you refer to the rust command line development documentation.

**Comment by HomyeeKing** [comment]
it does because the `rsw-watch` run in background and can't receive the `ctrl_c` signal, I recommend that use `concurrently`  instead of `&` in `vite-plugin-rsw` docs
